"""The acceptance scenario, published and then read back out of the files.

One completed investigation — payment failures by method and reason for 2026 —
is published as a Monthly Business Review in both formats, and every claim about
the result is checked against the generated bytes rather than against the code
that produced them. A test that asserted on the compiled model would pass while
a renderer quietly dropped a section.

Nothing here calls a model. The run is a fixture; publishing is assembly.
"""

from __future__ import annotations

import asyncio
import zipfile
from hashlib import sha256
from pathlib import Path
from uuid import uuid4

import pytest
from docx import Document
from pypdf import PdfReader

from app.analytics.presentation.templates import ReportTemplateRegistry
from app.artifacts.contracts import Artifact, ArtifactStatus
from app.artifacts.store import WorkspaceArtifactStore
from app.environment.workspace import Workspace
from app.orchestration.publishing import ReportPublisher
from tests.fixtures.payment_failures import (
    CAVEATS,
    FAILURE_BREAKDOWN,
    METHOD_TOTALS,
    PERIOD,
    RUN_ID,
    answer_sources,
    conversation_store,
)

TEMPLATE = "monthly_business_review"
WORKSPACE_ID = uuid4()

#: The eight sections the deliverable must carry. ``cover`` prints the title
#: page rather than a heading, so it is verified by its content below.
REQUIRED_HEADINGS = [
    "Reporting Scope", "Executive Summary", "Headline Metrics",
    "Charts", "Supporting Tables", "Limitations", "Evidence Appendix",
]
#: Citations the run actually executed. ``query_009`` was cited but never ran.
EXPECTED_CITATIONS = ["query_001", "query_002", "query_003"]
UNKNOWN_CITATION = "query_009"
#: Tables the cited queries read, which the Scope section must list.
EXPECTED_TABLES = ["payments", "payment_methods"]


def _publish(tmp_path: Path, formats=("pdf", "docx")) -> tuple[list[Artifact], WorkspaceArtifactStore]:
    workspace = Workspace(tmp_path)
    artifacts = WorkspaceArtifactStore(workspace, max_artifact_bytes=10_485_760)
    publisher = ReportPublisher(
        ReportTemplateRegistry(), conversation_store(), artifacts, workspace,
    )
    published = asyncio.run(publisher.publish(
        workspace_id=WORKSPACE_ID, run_id=RUN_ID, template_name=TEMPLATE, formats=list(formats), period=PERIOD,
    ))
    return published, artifacts


def _path(artifact: Artifact, artifacts: WorkspaceArtifactStore) -> Path:
    resolved = asyncio.run(artifacts.path_for(workspace_id=WORKSPACE_ID, artifact_id=artifact.id))
    assert resolved is not None, f"{artifact.name} did not resolve to a file"
    return resolved


def _pdf_text(path: Path) -> str:
    return " ".join("\n".join(page.extract_text() for page in PdfReader(str(path)).pages).split())


def _docx(path: Path) -> Document:
    return Document(str(path))


def _docx_text(path: Path) -> str:
    document = _docx(path)
    parts = [paragraph.text for paragraph in document.paragraphs]
    for table in document.tables:
        parts.extend(cell.text for row in table.rows for cell in row.cells)
    return " ".join(" ".join(parts).split())


@pytest.fixture(scope="module")
def published(tmp_path_factory):
    """Publish once; every check below reads the same two files."""

    directory = tmp_path_factory.mktemp("acceptance")
    artifacts, store = _publish(directory)
    by_format = {artifact.output_format: artifact for artifact in artifacts}
    return {
        "artifacts": by_format,
        "store": store,
        "pdf": _path(by_format["pdf"], store),
        "docx": _path(by_format["docx"], store),
    }


# ------------------------------------------------------------- both formats


def test_both_formats_are_produced(published) -> None:
    assert set(published["artifacts"]) == {"pdf", "docx"}
    for artifact in published["artifacts"].values():
        assert artifact.status is ArtifactStatus.READY
        assert artifact.template_id == TEMPLATE
        assert artifact.artifact_type == "report_document"


@pytest.mark.parametrize("fmt", ["pdf", "docx"])
def test_every_required_section_is_present(published, fmt: str) -> None:
    text = _pdf_text(published["pdf"]) if fmt == "pdf" else _docx_text(published["docx"])

    for heading in REQUIRED_HEADINGS:
        assert heading in text, f"{fmt} is missing the {heading} section"


@pytest.mark.parametrize("fmt", ["pdf", "docx"])
def test_the_cover_identifies_the_report(published, fmt: str) -> None:
    """The cover is a title page rather than a headed section."""

    text = _pdf_text(published["pdf"]) if fmt == "pdf" else _docx_text(published["docx"])

    assert "Monthly Business Review" in text
    assert PERIOD in text
    assert "Generated" in text


def test_the_docx_orders_its_sections_as_the_template_declares(published) -> None:
    headings = [item.text for item in _docx(published["docx"]).paragraphs
                if item.style.name.startswith("Heading")]

    positions = [headings.index(heading) for heading in REQUIRED_HEADINGS]
    assert positions == sorted(positions), f"sections are out of order: {headings}"


@pytest.mark.parametrize("fmt", ["pdf", "docx"])
def test_every_executed_query_is_cited(published, fmt: str) -> None:
    text = _pdf_text(published["pdf"]) if fmt == "pdf" else _docx_text(published["docx"])

    for citation in EXPECTED_CITATIONS:
        assert citation in text, f"{fmt} does not cite {citation}"


@pytest.mark.parametrize("fmt", ["pdf", "docx"])
def test_an_unknown_citation_never_appears(published, fmt: str) -> None:
    """It was cited by the answer and dropped because the run never ran it."""

    text = _pdf_text(published["pdf"]) if fmt == "pdf" else _docx_text(published["docx"])

    assert UNKNOWN_CITATION not in text
    resolved, unresolved = answer_sources()
    assert unresolved == [UNKNOWN_CITATION]
    assert [source.id for source in resolved] == EXPECTED_CITATIONS


@pytest.mark.parametrize("fmt", ["pdf", "docx"])
def test_the_scope_section_lists_the_tables_consulted(published, fmt: str) -> None:
    text = _pdf_text(published["pdf"]) if fmt == "pdf" else _docx_text(published["docx"])

    assert "Tables consulted" in text
    for table in EXPECTED_TABLES:
        assert table in text, f"{fmt} scope omits {table}"
    assert "Queries executed" in text and "Run reference" in text


@pytest.mark.parametrize("fmt", ["pdf", "docx"])
def test_every_stated_limitation_is_printed(published, fmt: str) -> None:
    text = _pdf_text(published["pdf"]) if fmt == "pdf" else _docx_text(published["docx"])

    for caveat in CAVEATS:
        assert caveat in text, f"{fmt} omits a stated limitation"
    # And the notice about what a citation does not prove.
    assert "do not independently verify" in text


@pytest.mark.parametrize("fmt", ["pdf", "docx"])
def test_the_appendix_restates_the_exact_charted_rows(published, fmt: str) -> None:
    """Every row behind the stacked bar must be checkable by hand."""

    text = _pdf_text(published["pdf"]) if fmt == "pdf" else _docx_text(published["docx"])

    assert "Rows shown in Figure 1" in text
    for row in FAILURE_BREAKDOWN:
        assert row["failure_reason"] in text
        assert f"{row['failure_count']:,}" in text, f"{row} missing from the appendix"
    assert "Returned columns" in text


@pytest.mark.parametrize("fmt", ["pdf", "docx"])
def test_the_supporting_table_is_embedded(published, fmt: str) -> None:
    text = _pdf_text(published["pdf"]) if fmt == "pdf" else _docx_text(published["docx"])

    assert "Failures and attempted value by method" in text
    for row in METHOD_TOTALS:
        assert row["payment_method"] in text
        assert f"{row['failure_count']:,}" in text


@pytest.mark.parametrize("fmt", ["pdf", "docx"])
def test_headline_metrics_carry_their_source_cell(published, fmt: str) -> None:
    text = _pdf_text(published["pdf"]) if fmt == "pdf" else _docx_text(published["docx"])

    assert "Failed attempts" in text and "10,732" in text
    assert "Attempted value" in text and "$23.4M" in text
    # Where the figure was read from, not merely which query it came from.
    assert "column failure_count" in text


# --------------------------------------------------------------------- PDF


def test_the_pdf_embeds_the_chart_as_an_image(published) -> None:
    reader = PdfReader(str(published["pdf"]))

    images = sum(len(page.images) for page in reader.pages)
    assert images >= 1, "the stacked bar was not embedded"


def test_the_pdf_numbers_every_page_and_repeats_its_header(published) -> None:
    reader = PdfReader(str(published["pdf"]))

    assert len(reader.pages) > 1
    for number, page in enumerate(reader.pages, start=1):
        text = " ".join(page.extract_text().split())
        assert f"Page {number}" in text
        assert "Monthly Business Review" in text
        assert RUN_ID in text


def test_the_page_break_puts_the_appendix_on_its_own_page(published) -> None:
    pages = [" ".join(page.extract_text().split()) for page in PdfReader(str(published["pdf"])).pages]

    appendix = next(index for index, text in enumerate(pages) if "Evidence Appendix" in text)
    limitations = next(index for index, text in enumerate(pages) if "Limitations" in text)
    assert appendix > limitations, "the appendix did not start after the limitations"


# -------------------------------------------------------------------- DOCX


def test_the_docx_embeds_the_chart_image(published) -> None:
    document = _docx(published["docx"])

    images = [rel for rel in document.part.rels.values() if "image" in rel.reltype]
    assert len(images) == 1, "expected exactly the stacked bar"


def test_the_docx_carries_readable_tables(published) -> None:
    tables = _docx(published["docx"]).tables

    assert tables, "no tables were written"
    for table in tables:
        assert len(table.columns) >= 2
        assert "tblHeader" in table.rows[0]._tr.xml, "a table heading will not repeat"


def test_the_docx_says_it_is_an_editable_copy_and_names_the_authority(published) -> None:
    """Word cannot guarantee a figure once a reader opens it."""

    text = _docx_text(published["docx"])

    assert "provided for editing and reuse" in text
    assert "the PDF is the published report" in text


def test_the_docx_escapes_rather_than_interprets_its_text(published) -> None:
    document = zipfile.ZipFile(published["docx"]).read("word/document.xml").decode()

    assert "<script" not in document.lower()


# ------------------------------------------------------------- artifact record


@pytest.mark.parametrize("fmt", ["pdf", "docx"])
def test_the_record_states_the_bytes_that_were_written(published, fmt: str) -> None:
    artifact = published["artifacts"][fmt]
    path = published[fmt]

    data = path.read_bytes()
    assert artifact.size == len(data)
    assert artifact.sha256 == sha256(data).hexdigest()
    # And the key is provider-independent, so it resolves elsewhere.
    assert artifact.relative_path == f"artifacts/{RUN_ID}/{artifact.id}/{artifact.name}"
    assert not Path(artifact.relative_path).is_absolute()


def test_publishing_this_run_reaches_no_model() -> None:
    """Asserting no call was made would pass trivially; the graph is the proof."""

    import ast
    from collections import deque

    from tests.support import BACKEND_ROOT

    def path_of(name: str):
        base = BACKEND_ROOT / name.replace(".", "/")
        for candidate in (base.with_suffix(".py"), base / "__init__.py"):
            if candidate.is_file():
                return candidate
        return None

    seen, queue = set(), deque(["app.orchestration.publishing"])
    while queue:
        name = queue.popleft()
        path = path_of(name)
        if name in seen or path is None:
            continue
        seen.add(name)
        for node in ast.walk(ast.parse(path.read_text())):
            if isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("app."):
                queue.append(node.module)
            elif isinstance(node, ast.Import):
                queue.extend(alias.name for alias in node.names if alias.name.startswith("app."))

    assert not [name for name in seen if name.startswith("app.llm")]
