/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agent/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Agent
         * @description Run the runtime for one submitted goal.
         */
        post: operations["run_agent_agent_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_analytics_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_analytics_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_v1_analytics_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/runs/{run_id}/events/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event History
         * @description Return the same safe public event projection used by SSE for an in-process run.
         */
        get: operations["get_event_history_api_v1_analytics_runs__run_id__events_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Update Conversation */
        patch: operations["update_conversation_api_v1_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/v1/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memory */
        get: operations["list_memory_api_v1_memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory */
        get: operations["get_memory_api_v1_memory__memory_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Schema */
        get: operations["search_schema_api_v1_schema_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tables */
        get: operations["list_tables_api_v1_schema_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/tables/{table_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe Table */
        get: operations["describe_table_api_v1_schema_tables__table_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/tables/{table_name}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Table Relationships */
        get: operations["table_relationships_api_v1_schema_tables__table_name__relationships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval */
        get: operations["get_approval_approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approval_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_approvals__approval_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approval_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_approvals__approval_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Artifact
         * @description Download a registered artifact by validated ID, never by a supplied path.
         */
        get: operations["download_artifact_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Artifact
         * @description Return only bounded, non-executable previews of registered artifacts.
         */
        get: operations["preview_artifact_artifacts__artifact_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Approvals */
        get: operations["list_approvals_runs__run_id__approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Trace
         * @description Return a sanitized trace; V7.1 traces are only retained until process restart.
         */
        get: operations["get_run_trace_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentRunRequest
         * @description A user goal submitted to the agent runtime.
         */
        AgentRunRequest: {
            /** Goal */
            goal: string;
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * AgentRunResponse
         * @description The current result of an agent run.
         */
        AgentRunResponse: {
            /** Artifacts */
            artifacts?: components["schemas"]["Artifact"][];
            /** Completed */
            completed: boolean;
            /** Duplicate Action Count */
            duplicate_action_count: number;
            /** Final Answer */
            final_answer: string | null;
            /** Iteration Count */
            iteration_count: number;
            /** Recoverable Error Count */
            recoverable_error_count: number;
            /** Run Id */
            run_id: string;
            /** Skills Used */
            skills_used: string[];
            status: components["schemas"]["RunStatus"];
            stop_reason: components["schemas"]["StopReason"] | null;
            /** Tool Call Count */
            tool_call_count: number;
            /** Tool Outcomes */
            tool_outcomes: components["schemas"]["ToolOutcomeSummary"][];
            /** Tools Used */
            tools_used: string[];
        };
        /** ApprovalResponse */
        ApprovalResponse: {
            /** Action Fingerprint */
            action_fingerprint: string;
            /** Agent Name */
            agent_name: string;
            /** Argument Summary */
            argument_summary: {
                [key: string]: string | number | boolean | null;
            };
            capability: components["schemas"]["Capability"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /** Id */
            id: string;
            /** Parent Run Id */
            parent_run_id: string | null;
            /** Policy Id */
            policy_id: string;
            /** Reason */
            reason: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Resource */
            resource: string | null;
            /** Run Id */
            run_id: string;
            status: components["schemas"]["ApprovalStatus"];
            /** Tool Name */
            tool_name: string;
        };
        /**
         * ApprovalStatus
         * @enum {string}
         */
        ApprovalStatus: "pending" | "approved" | "rejected" | "expired" | "cancelled";
        /**
         * Artifact
         * @description A registered file output, deliberately separate from observations and memory.
         */
        Artifact: {
            /** Artifact Type */
            artifact_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Media Type */
            media_type: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Relative Path */
            relative_path: string;
            /** Run Id */
            run_id: string;
            /** Size */
            size: number;
        };
        /** ArtifactMetadata */
        ArtifactMetadata: {
            /** Artifact Id */
            artifact_id: string;
            /** Created At */
            created_at: unknown;
            /** Media Type */
            media_type: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Run Id */
            run_id: string;
            /** Size */
            size: number;
            /** Type */
            type: string;
        };
        /**
         * Capability
         * @enum {string}
         */
        Capability: "calculator.evaluate" | "filesystem.read" | "filesystem.write" | "command.execute" | "python.execute" | "repository.read" | "repository.write" | "artifact.create" | "agent.delegate" | "web.search" | "database.schema.read" | "database.query.read" | "analytics.python.execute" | "analytics.report.create" | "database.metric.read";
        /**
         * ChartFormatting
         * @description Small, non-executable formatting vocabulary for the shared renderer.
         */
        ChartFormatting: {
            /** Currency */
            currency?: string | null;
            /** Decimal Places */
            decimal_places?: number | null;
            /**
             * Show Legend
             * @default true
             */
            show_legend: boolean;
        };
        /** ChartSeries */
        ChartSeries: {
            /** Field */
            field: string;
            /** Label */
            label?: string | null;
        };
        /**
         * ChartSpec
         * @description A bounded, declarative display produced from trusted query results.
         */
        ChartSpec: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            }[];
            /** Description */
            description?: string | null;
            formatting?: components["schemas"]["ChartFormatting"];
            /** Id */
            id?: string;
            /** Kpis */
            kpis?: components["schemas"]["KPIItem"][];
            /** Series */
            series?: components["schemas"]["ChartSeries"][];
            /** Source Query Ids */
            source_query_ids?: string[];
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "line" | "bar" | "stacked_bar" | "area" | "pie" | "scatter" | "table" | "kpi";
            /** X Field */
            x_field?: string | null;
            /** Y Fields */
            y_fields?: string[];
        };
        /** ConversationCreateRequest */
        ConversationCreateRequest: {
            /**
             * Title
             * @default New conversation
             */
            title: string;
        };
        /** ConversationDetailResponse */
        ConversationDetailResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Messages */
            messages: components["schemas"]["MessageResponse"][];
            /** Messages Limit */
            messages_limit: number;
            /** Messages Offset */
            messages_offset: number;
            /** Messages Total */
            messages_total: number;
            /** Runs */
            runs?: components["schemas"]["RunHistoryResponse"][];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConversationListResponse */
        ConversationListResponse: {
            /** Items */
            items: components["schemas"]["ConversationResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ConversationResponse */
        ConversationResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConversationTitleRequest */
        ConversationTitleRequest: {
            /** Title */
            title: string;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Message */
            message: string;
        };
        /** CreateRunResponse */
        CreateRunResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @constant
             */
            status: "running";
        };
        /** DatabaseColumn */
        DatabaseColumn: {
            /** Data Type */
            data_type: string;
            /** Foreign Key Target */
            foreign_key_target?: string | null;
            /** Name */
            name: string;
            /** Nullable */
            nullable: boolean;
            /**
             * Primary Key
             * @default false
             */
            primary_key: boolean;
        };
        /** DatabaseSchemaSummary */
        DatabaseSchemaSummary: {
            /** Schemas */
            schemas: string[];
            /** Tables */
            tables: components["schemas"]["DatabaseTable"][];
        };
        /** DatabaseTable */
        DatabaseTable: {
            /** Name */
            name: string;
            /** Schema */
            schema: string;
        };
        /** ForeignKeyRelationship */
        ForeignKeyRelationship: {
            /** Source Column */
            source_column: string;
            /** Source Schema */
            source_schema: string;
            /** Source Table */
            source_table: string;
            /** Target Column */
            target_column: string;
            /** Target Schema */
            target_schema: string;
            /** Target Table */
            target_table: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KPIItem */
        KPIItem: {
            /** Change */
            change?: string | null;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * MemoryType
         * @description The domain role a memory plays for the agent.
         * @enum {string}
         */
        MemoryType: "working" | "episodic" | "long_term";
        /** MessageResponse */
        MessageResponse: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Run Id */
            run_id?: string | null;
        };
        /**
         * PublicRunEvent
         * @description A deliberately small event envelope; never a serialized runtime object.
         */
        PublicRunEvent: {
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Type */
            type: string;
        };
        /** PublicRunEventListResponse */
        PublicRunEventListResponse: {
            /** Items */
            items: components["schemas"]["PublicRunEvent"][];
        };
        /** RunHistoryResponse */
        RunHistoryResponse: {
            /** Charts */
            charts?: components["schemas"]["ChartSpec"][];
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            metrics?: components["schemas"]["RunMetricsResponse"] | null;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed" | "waiting_for_approval";
        };
        /**
         * RunMetrics
         * @description Derived run-local performance and economic summary from trace events.
         */
        RunMetrics: {
            /** Cached Input Tokens */
            cached_input_tokens?: number | null;
            /**
             * Database Query Count
             * @default 0
             */
            database_query_count: number;
            /**
             * Database Query Duration Ms
             * @default 0
             */
            database_query_duration_ms: number;
            /**
             * Database Rejected Query Count
             * @default 0
             */
            database_rejected_query_count: number;
            /**
             * Database Rows Returned
             * @default 0
             */
            database_rows_returned: number;
            /**
             * Database Timeout Count
             * @default 0
             */
            database_timeout_count: number;
            /**
             * Delegation Duration Ms
             * @default 0
             */
            delegation_duration_ms: number;
            /**
             * Delegations
             * @default 0
             */
            delegations: number;
            /** Estimated Cost */
            estimated_cost?: number | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /**
             * Iterations
             * @default 0
             */
            iterations: number;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Llm Duration Ms
             * @default 0
             */
            llm_duration_ms: number;
            /**
             * Memory Duration Ms
             * @default 0
             */
            memory_duration_ms: number;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Reasoning Tokens */
            reasoning_tokens?: number | null;
            /**
             * Summary Duration Ms
             * @default 0
             */
            summary_duration_ms: number;
            /**
             * Tool Calls
             * @default 0
             */
            tool_calls: number;
            /**
             * Tool Duration Ms
             * @default 0
             */
            tool_duration_ms: number;
            /** Total Duration Ms */
            total_duration_ms?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /** RunMetricsResponse */
        RunMetricsResponse: {
            /**
             * Database Query Count
             * @default 0
             */
            database_query_count: number;
            /**
             * Database Rejected Query Count
             * @default 0
             */
            database_rejected_query_count: number;
            /**
             * Database Rows Returned
             * @default 0
             */
            database_rows_returned: number;
            /**
             * Delegations
             * @default 0
             */
            delegations: number;
            /** Estimated Cost */
            estimated_cost?: number | null;
            /**
             * Iterations
             * @default 0
             */
            iterations: number;
            /**
             * Tool Calls
             * @default 0
             */
            tool_calls: number;
            /** Total Duration Ms */
            total_duration_ms?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /** RunResponse */
        RunResponse: {
            /** Charts */
            charts?: components["schemas"]["ChartSpec"][];
            /** Conversation Id */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Final Response */
            final_response?: string | null;
            /** Finished At */
            finished_at?: string | null;
            metrics?: components["schemas"]["RunMetricsResponse"] | null;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed" | "waiting_for_approval";
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "running" | "waiting_for_approval" | "completed" | "failed";
        /** RunTrace */
        RunTrace: {
            /** Agent Name */
            agent_name: string;
            /** Agent Type */
            agent_type: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Ended At */
            ended_at?: string | null;
            /** Events */
            events?: components["schemas"]["TraceEvent"][];
            /** Goal */
            goal: string;
            metrics?: components["schemas"]["RunMetrics"];
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Run Id */
            run_id: string;
            /** Spans */
            spans?: components["schemas"]["TraceSpan"][];
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** @default running */
            status: components["schemas"]["TraceStatus"];
            /** Stop Reason */
            stop_reason?: string | null;
        };
        /**
         * StopReason
         * @description Why an agent run reached its terminal state.
         * @enum {string}
         */
        StopReason: "completed" | "max_iterations" | "max_tool_calls" | "too_many_errors" | "cancelled" | "fatal_error";
        /** TableDescription */
        TableDescription: {
            /** Columns */
            columns: components["schemas"]["DatabaseColumn"][];
            /** Foreign Keys */
            foreign_keys?: components["schemas"]["ForeignKeyRelationship"][];
            /** Name */
            name: string;
            /** Primary Key */
            primary_key?: string[];
            /** Schema */
            schema: string;
            /** Unique Constraints */
            unique_constraints?: string[][];
        };
        /**
         * ToolOutcomeSummary
         * @description Safe execution information useful when reviewing an agent run.
         */
        ToolOutcomeSummary: {
            /**
             * Blocked As Duplicate
             * @default false
             */
            blocked_as_duplicate: boolean;
            /** Error */
            error?: string | null;
            /** Success */
            success: boolean;
            /** Tool Name */
            tool_name: string;
        };
        /** TraceEvent */
        TraceEvent: {
            /** Child Run Id */
            child_run_id?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Event Id */
            event_id?: string;
            event_type: components["schemas"]["TraceEventType"];
            /** Iteration */
            iteration?: number | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /** Run Id */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            status?: components["schemas"]["TraceStatus"] | null;
            /** Success */
            success?: boolean | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /**
         * TraceEventType
         * @enum {string}
         */
        TraceEventType: "run_started" | "run_finished" | "run_failed" | "llm_request_started" | "llm_request_finished" | "llm_request_failed" | "tool_started" | "tool_finished" | "tool_failed" | "skill_loaded" | "memory_retrieval_started" | "memory_retrieval_finished" | "task_summary_started" | "task_summary_finished" | "delegation_started" | "delegation_finished" | "parallel_delegation_started" | "parallel_delegation_finished" | "security_policy_evaluated" | "approval_requested" | "approval_resolved" | "artifact_created" | "operation_failed" | "retry_scheduled" | "retry_started" | "retry_succeeded" | "retry_exhausted" | "database_schema_listed" | "database_table_described" | "database_relationships_inspected" | "database_schema_searched" | "database_query_validation_started" | "database_query_validated" | "database_query_rejected" | "database_query_started" | "database_query_finished" | "database_query_failed" | "analytics_python_started" | "analytics_python_finished" | "analytics_python_failed" | "chart_created" | "report_created";
        /** TraceSpan */
        TraceSpan: {
            /** Duration Ms */
            duration_ms?: number | null;
            /** Ended At */
            ended_at?: string | null;
            event_type: components["schemas"]["TraceEventType"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /** Run Id */
            run_id: string;
            /** Span Id */
            span_id?: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** @default running */
            status: components["schemas"]["TraceStatus"];
        };
        /**
         * TraceStatus
         * @enum {string}
         */
        TraceStatus: "running" | "completed" | "failed" | "waiting_for_approval";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    run_agent_agent_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_analytics_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_analytics_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_analytics_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_history_api_v1_analytics_runs__run_id__events_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicRunEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_conversations__conversation_id__get: {
        parameters: {
            query?: {
                message_limit?: number;
                message_offset?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_v1_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationTitleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memory_api_v1_memory_get: {
        parameters: {
            query?: {
                memory_type?: components["schemas"]["MemoryType"] | null;
                run_id?: string | null;
                session_id?: string | null;
                created_after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_api_v1_memory__memory_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_schema_api_v1_schema_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseTable"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tables_api_v1_schema_tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseSchemaSummary"];
                };
            };
        };
    };
    describe_table_api_v1_schema_tables__table_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableDescription"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    table_relationships_api_v1_schema_tables__table_name__relationships_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForeignKeyRelationship"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_approvals__approval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_approvals__approval_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_approvals__approval_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_artifacts_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactMetadata"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_artifact_artifacts__artifact_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_approvals_runs__run_id__approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_trace_runs__run_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
