"""Run a compiled metric and return an immutable result.

The sequence is fixed and there is no way around it: compile, validate the
compiled text with the same AST validator the agent's own SQL goes through,
then execute read-only under the configured timeout and row limit. A compiled
statement gets no more trust than a written one — being generated by the
runtime is not evidence that it is safe, so it is checked anyway.

The result is frozen. Everything downstream reads values from it; nothing
recomputes one.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from app.analytics.connection import AnalyticsDatabaseError
from app.analytics.schema.inspector import PostgreSQLInspector
from app.analytics.semantics.compiler import (
    CompiledMetricQuery,
    MetricCompilationError,
    compile_metric,
)
from app.analytics.semantics.metrics import MetricDefinition, MetricRegistry
from app.analytics.semantics.parameters import MetricParameters
from app.analytics.sql.executor import AnalyticsQueryError, AnalyticsSQLExecutor
from app.analytics.sql.validator import PostgreSQLQueryValidator


@dataclass(frozen=True, slots=True)
class MetricResult:
    """One executed metric, and everything needed to account for it.

    Frozen because a report prints these values and an appendix cites them; a
    result that could be edited after execution would make both a guess.
    """

    metric: str
    metric_version: str
    display_name: str
    format: str
    unit: str
    parameters: MetricParameters
    columns: tuple[str, ...]
    dimension_columns: tuple[str, ...]
    value_columns: tuple[str, ...]
    rows: tuple[dict[str, Any], ...]
    tables_consulted: tuple[str, ...]
    row_count: int
    truncated: bool
    executed_at: datetime
    execution_ms: int
    sql_fingerprint: str

    @property
    def is_empty(self) -> bool:
        return not self.rows


class MetricExecutionError(RuntimeError):
    """Raised when a compiled metric could not be run."""


class MetricRunner:
    """Compile, validate and execute one metric request."""

    def __init__(self, registry: MetricRegistry, validator: PostgreSQLQueryValidator,
                 executor: AnalyticsSQLExecutor, inspector: PostgreSQLInspector) -> None:
        self._registry = registry
        self._validator = validator
        self._executor = executor
        self._inspector = inspector

    def definition(self, name: str) -> MetricDefinition:
        metric = self._registry.get_metric_definition(name)
        if metric is None:
            raise MetricCompilationError(f"Unknown metric: {name}.")
        return metric

    def compile(self, parameters: MetricParameters) -> CompiledMetricQuery:
        return compile_metric(self.definition(parameters.metric), parameters)

    async def run(self, parameters: MetricParameters) -> MetricResult:
        """Execute one metric request, refusing anything the validator rejects."""

        metric = self.definition(parameters.metric)
        compiled = compile_metric(metric, parameters)

        try:
            summary = await self._inspector.list_tables()
        except AnalyticsDatabaseError as error:
            raise MetricExecutionError("The analytics database is unavailable.") from error

        # The same gate the agent's SQL passes through. A compiled statement is
        # not exempt: if this ever disagrees with the compiler, the validator
        # wins and nothing runs.
        validation = self._validator.validate(
            compiled.sql, allowed_tables=[table.name for table in summary.tables]
        )
        if not validation.valid:
            raise MetricExecutionError(
                f"The compiled {metric.display_name} query was rejected: {validation.reason}"
            )

        try:
            result = await self._executor.execute(
                compiled.sql,
                referenced_tables=validation.referenced_tables,
                parameters=compiled.parameters,
            )
        except AnalyticsQueryError as error:
            raise MetricExecutionError(f"{metric.display_name} could not be recomputed.") from error

        names = [column.name for column in result.columns]
        return MetricResult(
            metric=metric.name,
            metric_version=metric.version,
            display_name=metric.display_name,
            format=metric.format,
            unit=metric.unit,
            parameters=parameters,
            columns=tuple(names),
            dimension_columns=compiled.dimension_columns,
            value_columns=compiled.value_columns,
            rows=tuple(dict(zip(names, row, strict=True)) for row in result.rows),
            tables_consulted=tuple(validation.referenced_tables),
            row_count=result.row_count,
            truncated=result.truncated,
            executed_at=datetime.now(timezone.utc),
            execution_ms=result.execution_ms,
            sql_fingerprint=compiled.fingerprint,
        )
